server:
  port: 8080

spring:
  application:
    name: bankpay-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: BankPay Service
    version: 1.0.0
