pipeline {

agent {
kubernetes {
yaml '''
apiVersion: v1
kind: Pod
spec:
containers:
- name: builder
image: maven:3.9.6-eclipse-temurin-17
command: ["cat"]
tty: true
'''
}
}

environment {
APP_NAME       = "bankpay-service"
DOCKERHUB_USER = "riteshsingh90"
IMAGE_NAME     = "${DOCKERHUB_USER}/${APP_NAME}"
IMAGE_TAG      = "${BUILD_NUMBER}"
SONAR_URL      = "http://sonarqube.bankpay.local:30001"
HELM_CHART     = "helm/bankpay"
}

stages {

```
stage('Checkout') {
  steps {
    checkout scm
  }
}

stage('Build & Test') {
  steps {
    container('builder') {
      dir('app') {
        sh 'mvn clean package -DskipTests'
        sh 'mvn test'
      }
    }
  }
}

stage('SonarQube') {
  steps {
    container('builder') {
      dir('app') {
        withSonarQubeEnv('SonarQube-Server') {
          sh """
            mvn sonar:sonar \
            -Dsonar.projectKey=bankpay-service \
            -Dsonar.host.url=${SONAR_URL}
          """
        }
      }
    }
  }
}

stage('Quality Gate') {
  steps {
    timeout(time: 5, unit: 'MINUTES') {
      waitForQualityGate abortPipeline: true
    }
  }
}

stage('Build & Push Image (Kaniko)') {
  steps {
    container('builder') {
      withCredentials([usernamePassword(
        credentialsId: 'dockerhub-creds',
        usernameVariable: 'DOCKER_USER',
        passwordVariable: 'DOCKER_PASS'
      )]) {

        sh '''
        echo "Downloading Kaniko..."
        curl -sSL https://github.com/GoogleContainerTools/kaniko/releases/download/v1.23.2/executor-linux-amd64 -o /kaniko
        chmod +x /kaniko

        mkdir -p /kaniko/.docker

        echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_PASS\"}}}" > /kaniko/.docker/config.json

        echo "Running Kaniko..."
        /kaniko \
          --dockerfile=app/Dockerfile \
          --context=$(pwd)/app \
          --destination=$DOCKER_USER/bankpay-service:${BUILD_NUMBER} \
          --destination=$DOCKER_USER/bankpay-service:latest
        '''
      }
    }
  }
}

stage('Deploy') {
  steps {
    sh """
      helm upgrade --install bankpay-dev \
      ${HELM_CHART} \
      --namespace bankpay-dev \
      --values ${HELM_CHART}/values-dev.yaml \
      --set image.repository=${IMAGE_NAME} \
      --set image.tag=${IMAGE_TAG} \
      --wait
    """
  }
}
```

}

}
