replicaCount: 1

image:
  repository: riteshsingh90/bankpay-service
  tag: "55"
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  nodePort: 30003

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  APP_ENV: production

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 90
  periodSeconds: 10
  failureThreshold: 10
