replicaCount: 1

image:
  repository: riteshsingh90/bankpay-service
  tag: "latest"
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  nodePort: 30003

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  APP_ENV: production

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 5
